spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9093
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
server:
  port: 8080